npc = [
    "Aldric",
    "Vaelor",
    "Tharion",
    "Cedric",
    "Edran",
    "Kaelen",
    "Malric",
    "Roderic",
    "Garran",
    "Torren",
    "Alaric",
    "Serath",
    "Darian",
    "Varik",
    "Corvin",
    "Merek",
    "Brennar",
    "Orrin",
    "Theron",
    "Valdris"]

title = [
    "the Brave",
    "the Cruel",
    "the Mad",
    "the Wise",
    "the Conqueror",
    "the Betrayer",
    "the Oathbreaker",
    "the Unbroken",
    "the Forsaken",
    "the Exiled",
    "the Merciless",
    "the Wanderer",
    "the Nameless",
    "the Black",
    "the Red",
    "the Pale",
    "the Cursed",
    "the Undying",
    "the Lost",
    "the Last"]

weapon_names = [
    "Destiny",
    "Doom",
    "Fate",
    "Ruin",
    "Vengeance",
    "the Fallen",
    "the Ancients",
    "the Last King",
    "the Betrayer",
    "the Exile",
    "the Damned",
    "the Wanderer",
    "the First Flame",
    "the Black Sun",
    "the Old Gods",
    "the Deep",
    "the North",
    "the Void",
    "Ashes",
    "Eternity"]